### ISSUE TITLE
Upload artifact to GH artifacts?

### ISSUE THREAD

**Issue by asraa** [ianlewis/slsa-byob-template#19]
Since this runs as a reusable workflow, I can't run a step after in the same VM requesting to upload the artifact so a further job can consume it.

Does it make sense to upload the artifact as a step in https://github.com/ianlewis/slsa-byob-template/blob/a047bb0b0f7db5020b6172ed08e922b4cca25377/internal/action-wrapper/action.yml#L40?

rr

**Comment by ianlewis** [comment]
Yeah, It could be done here too
https://github.com/ianlewis/slsa-byob-template/blob/a047bb0b0f7db5020b6172ed08e922b4cca25377/.github/workflows/slsa3.yml#L77-L99

**Comment by asraa** [comment]
I think it makes more sense to do it inside the tool, only because the tool has actual knowledge of the path it writes to (and there are no outputs to the build step)

**Comment by asraa** [comment]
I believe this is fixed!
